// <auto-generated />
using System;
using Analytics.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Analytics.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Analytics.Domain.Models.PortfolioAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DailyChangePercent")
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalReturnPercent")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioAnalytics", (string)null);
                });

            modelBuilder.Entity("Analytics.Domain.Models.PortfolioAnalytics", b =>
                {
                    b.OwnsMany("Analytics.Domain.Models.AssetContribution", "AssetContributions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("CurrentValue")
                                .HasColumnType("decimal(18,4)");

                            b1.Property<Guid>("PortfolioAnalyticsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<decimal>("WeightPercent")
                                .HasColumnType("decimal(9,6)");

                            b1.HasKey("Id");

                            b1.HasIndex("PortfolioAnalyticsId");

                            b1.ToTable("AssetContributions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PortfolioAnalyticsId");
                        });

                    b.OwnsMany("Analytics.Domain.Models.PortfolioAnalyticsSnapshot", "Snapshots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("PortfolioAnalyticsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("datetime2");

                            b1.Property<decimal>("TotalValue")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("PortfolioAnalyticsId");

                            b1.ToTable("PortfolioAnalyticsSnapshots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PortfolioAnalyticsId");
                        });

                    b.OwnsOne("Analytics.Domain.ValueObjects.UserName", "User", b1 =>
                        {
                            b1.Property<Guid>("PortfolioAnalyticsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("UserName");

                            b1.HasKey("PortfolioAnalyticsId");

                            b1.ToTable("PortfolioAnalytics");

                            b1.WithOwner()
                                .HasForeignKey("PortfolioAnalyticsId");
                        });

                    b.Navigation("AssetContributions");

                    b.Navigation("Snapshots");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
